#!/usr/bin/env node

var linker = require('./'),
    concat = require('concat-stream');

process.stdin.pipe(concat(linkify));

function linkify(input) {
    process.stdout.write(linker.addCitationLinks(input.toString()));
}
